Add offline theme previewer
eclipse-color-theme/eclipse-color-theme pull request #244
Opened 2016-09-07 19:10 UTC by rainysaturday

Implements a theme previewer by using the browser widget.
Added a small html page "preview.html" which is used as a template for showing the theme.
Then creates a css from the theme object and inserts that into the html.
Fixes issue #70, make theme previews work offline.

2016-09-07 20:19 UTC, rainysaturday commented
I wasn't sure were to add to the CHANGES.md file, on 1.1.0?

* Added offline theme previewer

2016-09-09 12:05 UTC, rainysaturday commented
Sorry, I noticed some small errors in this pull request, I'll commit a fix later today for them.

2016-09-16 09:29 UTC, fhd commented on CHANGES.md
> +* Added offline theme previewer
Can you move this to the `1.1.0` section below?

2016-09-16 09:31 UTC, fhd requested changes
Looks great, thanks a lot for tackling this! I've only got a very minor comment, otherwise it's good to merge.

2016-09-16 20:50 UTC, rainysaturday commented
Hi, thanks for the response.
I'm new to github and fairly new to git so I think I messed up my repository a bit.
I made a new pull request  #247 which fixes your comment about CHANGES.md. I'll close this PR.
Thanks.

2016-09-16 20:50 UTC, closed without merging